#!/usr/bin/env python3
"""Lioreal Workshop Agent v0.2.

Self-healing, self-updating workshop operator. Runs workspace checks,
attempts to repair simple failures (--heal), records SHA256-signed
evidence, and updates workshop/NOW.md with the latest run state.

Does not call providers, deploy, merge, or touch production. Those
capabilities are added deliberately and reviewably behind explicit
permission flags.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
RUNS_DIR = ROOT / "workshop" / "runs"
NOW_FILE = ROOT / "workshop" / "NOW.md"
CHARTER_FILE = ROOT / "agent" / "CHARTER.md"
JOURNAL_FILE = ROOT / "workshop" / "journal" / "0000-the-workshop-exists.md"
MIGRATION_FILE = ROOT / "supabase" / "migrations" / "202607200001_lioreal_workshop_agent.sql"

ALLOWED_RISK_CLASSES = {
    "read_only",
    "reviewable_write",
    "steward_required",
    "forbidden",
}

# Sentinel bounds the section the agent owns in NOW.md.
# Content outside these markers is never touched.
NOW_SENTINEL_OPEN = "<!-- AGENT:LAST_RUN -->"
NOW_SENTINEL_CLOSE = "<!-- /AGENT:LAST_RUN -->"

NOW_TEMPLATE = """\
# NOW

## Current task

Agent self-heal: NOW.md was missing and has been regenerated.

## Active branch

{branch}

## Mode

Workshop Mode. Changes remain reviewable.

## Current build sequence

- [ ] Restore missing workshop documents
- [ ] Verify Ark continuity documents are intact
- [ ] Run agent checks and confirm all pass

## Current blocker

NOW.md was absent. A minimal template has been written. Rowan and Vee should
review and restore the intended state from git history if needed.

## Next action

```bash
python agent/lioreal_agent.py
```
"""

JOURNAL_STUB = """\
# Workshop Entry 0000 · The Workshop Exists

**Status:** stub — regenerated by agent heal
**Date:** {date}

## What happened?

The workshop journal was absent. This stub was created by the Lioreal Workshop
Agent during a self-healing run. Rowan and Vee should restore the original
entry from git history.
"""


@dataclass
class CheckResult:
    name: str
    ok: bool
    detail: str
    healed: bool = False


@dataclass
class AgentRun:
    run_key: str
    task: str
    mode: str
    risk_class: str
    status: str = "planned"
    branch_name: str | None = None
    starting_commit: str | None = None
    ending_commit: str | None = None
    started_at: str = field(default_factory=lambda: now_iso())
    finished_at: str | None = None
    checks: list[dict[str, Any]] = field(default_factory=list)
    healed: list[str] = field(default_factory=list)
    blocker: str | None = None
    summary: str | None = None


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def now_date() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def in_ci() -> bool:
    return os.environ.get("CI", "").lower() in ("true", "1", "yes")


def run_command(command: list[str]) -> tuple[int, str]:
    try:
        process = subprocess.run(
            command,
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return 1, str(exc)
    output = (process.stdout + process.stderr).strip()
    return process.returncode, output


def git_value(*args: str) -> str | None:
    code, output = run_command(["git", *args])
    return output.splitlines()[0] if code == 0 and output else None


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ── Checks ────────────────────────────────────────────────────────────────────

def inspect_workspace() -> list[CheckResult]:
    checks: list[CheckResult] = []

    checks.append(CheckResult(
        "NOW.md exists",
        NOW_FILE.exists(),
        str(NOW_FILE.relative_to(ROOT)),
    ))

    checks.append(CheckResult(
        "Agent charter exists",
        CHARTER_FILE.exists(),
        str(CHARTER_FILE.relative_to(ROOT)),
    ))

    checks.append(CheckResult(
        "Workshop Journal is open",
        JOURNAL_FILE.exists(),
        str(JOURNAL_FILE.relative_to(ROOT)),
    ))

    migration_ok = (
        MIGRATION_FILE.exists()
        and "create table public.agent_runs" in MIGRATION_FILE.read_text(encoding="utf-8")
    )
    checks.append(CheckResult(
        "Workshop lineage migration exists",
        migration_ok,
        str(MIGRATION_FILE.relative_to(ROOT)),
    ))

    code, output = run_command([sys.executable, "-m", "py_compile", str(Path(__file__))])
    checks.append(CheckResult(
        "Agent scaffold compiles",
        code == 0,
        output or "py_compile passed",
    ))

    return checks


# ── Healing ───────────────────────────────────────────────────────────────────

def heal_workspace(checks: list[CheckResult]) -> list[CheckResult]:
    """Attempt to repair failing checks within Workshop Mode permissions.

    Healing is conservative: only creates missing directories and
    regenerates documents from known templates. Canonical continuity
    records, the agent charter, and database migrations require Steward
    review and are never auto-recreated.
    """
    repaired: list[CheckResult] = []

    for check in checks:
        if check.ok:
            repaired.append(check)
            continue

        if check.name == "NOW.md exists":
            branch = git_value("branch", "--show-current") or "unknown"
            NOW_FILE.parent.mkdir(parents=True, exist_ok=True)
            NOW_FILE.write_text(NOW_TEMPLATE.format(branch=branch), encoding="utf-8")
            ok = NOW_FILE.exists()
            repaired.append(CheckResult(
                check.name, ok,
                "healed: created minimal NOW.md from template" if ok else "heal failed: could not write NOW.md",
                healed=ok,
            ))

        elif check.name == "Workshop Journal is open":
            JOURNAL_FILE.parent.mkdir(parents=True, exist_ok=True)
            if not JOURNAL_FILE.exists():
                JOURNAL_FILE.write_text(
                    JOURNAL_STUB.format(date=now_date()), encoding="utf-8"
                )
            ok = JOURNAL_FILE.exists()
            repaired.append(CheckResult(
                check.name, ok,
                "healed: created journal stub" if ok else "heal failed: could not write journal stub",
                healed=ok,
            ))

        elif check.name == "Agent charter exists":
            # The charter defines the agent's own authority — cannot be silently recreated.
            repaired.append(CheckResult(
                check.name, False,
                "steward-required: CHARTER.md is missing and must be restored from git history",
            ))

        elif check.name == "Workshop lineage migration exists":
            # Database migrations require explicit Steward review before creation.
            repaired.append(CheckResult(
                check.name, False,
                "steward-required: migration file is missing; restore from git history or run in Steward Mode",
            ))

        elif check.name == "Agent scaffold compiles":
            # Syntax errors in the agent itself cannot be self-healed at runtime.
            repaired.append(CheckResult(
                check.name, False,
                f"cannot self-heal syntax error — repair the agent source: {check.detail}",
            ))

        else:
            repaired.append(check)

    return repaired


# ── NOW.md update ─────────────────────────────────────────────────────────────

def update_now(run: AgentRun) -> None:
    """Append or replace the sentinel-bounded last-run section in NOW.md.

    Only the content between AGENT:LAST_RUN and /AGENT:LAST_RUN is
    written. Everything outside those markers is preserved exactly.
    """
    if not NOW_FILE.exists():
        return

    passed = sum(1 for c in run.checks if c.get("ok"))
    total = len(run.checks)
    healed_count = len(run.healed)

    heal_note = f"\n- Healed: {healed_count} item(s)" if healed_count else ""
    section = (
        f"{NOW_SENTINEL_OPEN}\n"
        f"## Last agent run\n\n"
        f"- Key: `{run.run_key}`\n"
        f"- Status: **{run.status}**\n"
        f"- At: `{run.finished_at}`\n"
        f"- Branch: `{run.branch_name}`\n"
        f"- Commit: `{run.ending_commit}`\n"
        f"- Checks: {passed}/{total} passed{heal_note}\n"
        + (f"- Blocker: {run.blocker}\n" if run.blocker else "")
        + f"\n_Updated automatically by `agent/lioreal_agent.py`. Do not edit this section manually._\n"
        f"{NOW_SENTINEL_CLOSE}\n"
    )

    text = NOW_FILE.read_text(encoding="utf-8")

    if NOW_SENTINEL_OPEN in text and NOW_SENTINEL_CLOSE in text:
        before = text[: text.index(NOW_SENTINEL_OPEN)]
        after = text[text.index(NOW_SENTINEL_CLOSE) + len(NOW_SENTINEL_CLOSE):]
        text = before + section + after
    else:
        separator = "\n\n" if not text.endswith("\n\n") else "\n"
        text = text.rstrip("\n") + separator + section

    NOW_FILE.write_text(text, encoding="utf-8")


# ── Run record ────────────────────────────────────────────────────────────────

def write_run(run: AgentRun) -> Path:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    path = RUNS_DIR / f"{run.run_key}.json"
    payload = asdict(run)
    payload["evidence_sha256"] = sha256_text(json.dumps(payload, sort_keys=True))
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


# ── Report ────────────────────────────────────────────────────────────────────

def render_report(run: AgentRun, run_path: Path | None) -> str:
    passed = sum(1 for c in run.checks if c.get("ok"))
    total = len(run.checks)
    lines = [
        "# Lioreal Workshop Agent Report",
        "",
        f"- Run key: `{run.run_key}`",
        f"- Status: **{run.status}**",
        f"- Branch: `{run.branch_name}`",
        f"- Commit: `{run.ending_commit}`",
        f"- Generated: `{run.finished_at}`",
        f"- Checks: {passed}/{total} passed",
        "",
        "## Checks",
        "",
    ]
    for check in run.checks:
        icon = "✅" if check.get("ok") else "❌"
        healed = " *(healed)*" if check.get("healed") else ""
        lines.append(f"{icon} **{check['name']}**{healed} — {check['detail']}")

    if run.healed:
        lines.extend(["", "## Healed", ""])
        for item in run.healed:
            lines.append(f"- {item}")

    if run.blocker:
        lines.extend(["", f"## Blocker\n\n{run.blocker}"])

    if run.summary:
        lines.extend(["", f"## Summary\n\n{run.summary}"])

    if run_path:
        lines.extend(["", f"Evidence written to `{run_path.relative_to(ROOT)}`"])

    lines.extend([
        "",
        "_Observation is autonomous. Adoption remains reviewable._",
        "",
    ])
    return "\n".join(lines)


# ── Execution ─────────────────────────────────────────────────────────────────

def execute(task: str, mode: str, risk_class: str, heal: bool) -> tuple[AgentRun, Path | None]:
    if risk_class not in ALLOWED_RISK_CLASSES:
        raise ValueError(f"Unknown risk class: {risk_class}")

    run = AgentRun(
        run_key=f"run-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid.uuid4().hex[:8]}",
        task=task,
        mode=mode,
        risk_class=risk_class,
        branch_name=git_value("branch", "--show-current"),
        starting_commit=git_value("rev-parse", "HEAD"),
    )

    if risk_class == "forbidden":
        run.status = "blocked"
        run.blocker = "The requested operation is forbidden by the Agent charter."
    elif risk_class == "steward_required" and mode != "steward":
        run.status = "blocked"
        run.blocker = "This operation requires Steward Mode and explicit approval."
    else:
        run.status = "running"
        checks = inspect_workspace()

        if heal and not in_ci():
            checks = heal_workspace(checks)
            run.healed = [c.name for c in checks if c.healed]

        run.checks = [asdict(c) for c in checks]
        failures = [c for c in checks if not c.ok]

        if failures:
            run.status = "failed"
            run.summary = f"{len(failures)} check(s) failed."
            if any("steward-required" in c.detail for c in failures):
                run.blocker = "One or more checks require Steward review. See check details."
        else:
            run.status = "completed"
            healed_note = f" ({len(run.healed)} healed)" if run.healed else ""
            run.summary = f"All checks passed{healed_note}."

    run.ending_commit = git_value("rev-parse", "HEAD")
    run.finished_at = now_iso()

    run_path = None
    if not in_ci():
        run_path = write_run(run)

    return run, run_path


# ── Entry point ───────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task", default="Inspect and maintain Lioreal Workshop Agent foundation")
    parser.add_argument("--mode", choices=("workshop", "steward"), default="workshop")
    parser.add_argument(
        "--risk-class",
        choices=sorted(ALLOWED_RISK_CLASSES),
        default="read_only",
    )
    parser.add_argument(
        "--heal",
        action="store_true",
        help="Attempt to repair failing checks within Workshop Mode permissions.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=None,
        help="Write a Markdown report to this path (used in CI).",
    )
    parser.add_argument(
        "--update-now",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Update workshop/NOW.md with the last-run state (disabled in CI automatically).",
    )
    parser.add_argument(
        "--fail-on-error",
        action="store_true",
        help="Exit non-zero if any check fails (useful in CI).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        run, run_path = execute(args.task, args.mode, args.risk_class, args.heal)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(json.dumps(asdict(run), indent=2, sort_keys=True))
    if run_path:
        print(f"Evidence: {run_path.relative_to(ROOT)}")

    if args.report:
        report_path = args.report if args.report.is_absolute() else ROOT / args.report
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(render_report(run, run_path), encoding="utf-8")
        print(f"Report: {report_path}")

    if args.update_now and not in_ci():
        update_now(run)

    if args.fail_on_error and run.status != "completed":
        return 1
    return 0 if run.status in ("completed", "blocked") else 1


if __name__ == "__main__":
    raise SystemExit(main())
